### ISSUE TITLE
Are you gonna PR this?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [91247686/National-Guard-Camp-edit#2]
@91247686 Are you gonna PR this? Apart from the decrease in bots, this looks quite interesting.

**Comment by 91247686** [comment]
I may, but there's still a little left to do before I'm satisfied with it.
  Mostly just things like changing those annoying doors to ones that can be opened (in some areas, at least) and fine-tuning the bot population ( I prefer not having unending hordes of them, but I think I may've reduced it a bit too much).

**Comment by BorkBorkGoesTheCode** [comment]
@91247686 Would you mind if I PR your late changes to coregame into this repository?
